github.com:
    users:
        kkau789:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: kkau789
